production:
    # Default log level is info
    loglevel: _env:LOGLEVEL:info
    # By default, the registry acts standalone (eg: doesn't query the index)
    standalone: True
    # Storage redirect is disabled
    storage_redirect: false
    # Token auth is enabled (if NOT standalone)
    disable_token_auth: true
    # No priv key
    privileged_key: _env:PRIVILEGED_KEY
    search_backend: _env:SEARCH_BACKEND:sqlalchemy
    # SQLite search backend
    sqlalchemy_index_database: _env:SQLALCHEMY_INDEX_DATABASE:sqlite:////tmp/docker-registry.db

    # Enabling these options makes the Registry send an email on each code Exception
    email_exceptions:
        smtp_host: _env:SMTP_HOST
        smtp_port: _env:SMTP_PORT:25
        smtp_login: _env:SMTP_LOGIN
        smtp_password: _env:SMTP_PASSWORD
        smtp_secure: _env:SMTP_SECURE:false
        from_addr: _env:SMTP_FROM_ADDR:docker-registry@localdomain.local
        to_addr: _env:SMTP_TO_ADDR:noise+dockerregistry@localdomain.local

    # Enable bugsnag (set the API key)
    bugsnag: _env:BUGSNAG
    storage_path: _env:STORAGE_PATH:/docker-registry

    storage: swift
    swift_authurl: _env:ORBIT_AUTH_URL:https://orbit.brightbox.com/v1
    swift_container: _env:ORBIT_CONTAINER
    swift_user: _env:CLIENT_ID
    swift_password: _env:CLIENT_SECRET
    swift_auth_version: 1

